apiVersion: networking.k8s.io/v1
kind: NetworkPolicy      #this policy is to block the cross ns communication
metadata:
  name: deny-cross-ns-comm 
  namespace: dev-team
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Ingress       #incoming
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: default