apiVersion: v1 
kind: LimitRange
metadata:
  name: devops-team-limit-range 
  namespace: devops-team 
spec:
  limits:
  - type: Pod
    min:
      cpu: "100m"
      memory: "100Mi"
    max:
      cpu: "200m"
      memory: "200Mi"