apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-file-vol
spec:
  capacity:
    storage: 1Ti
  nfs:
    path: /vol01 
    server: 10.196.1.34
  accessModes:
    - ReadWriteMany
  claimRef:
    name: manual-file-vol-claim
    namespace: default
  persistentVolumeReclaimPolicy: Retain