apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-deploy
  labels:
    app: httpd-app
spec:
  replicas: 20
  selector:
    matchLabels:
      app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      containers:
      - name: httpd-app
        image: httpd
        ports:
        - containerPort: 80