apiVersion: rbac.authorization.k8s.io/v1
kind: Role          #Namespace level access
metadata:
  name: pod-log-reader 
  namespace: dev-team 
rules:
- apiGroups:
    - ""
  resources:
    - nodes
    - pods
    - pods/log
  verbs: ["get","create","update","delete","list"] 