---
apiVersion: apps/v1
kind: Deployment #Controller
metadata:
  name: httpd-deploy
  labels:
    app: httpd
spec: 
  replicas: 10
  selector:
    matchLabels:
      app: httpd  
  template:
    metadata:
      name: simple-pod
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata: 
  name: httpd-lb-service 
  labels:
    app: httpd
spec:
  type: LoadBalancer #Layer4
  selector: 
    app: httpd 
  ports:
  - port: 80
    targetPort: 80