apiVersion: apps/v1 
kind: Deployment    #Controller
metadata:
  name: nginx-np
  labels:
    app: nginxnp 
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginxnp
  template:
    metadata:
      name: nginx-pod 
      labels:
        app: nginxnp
    spec:
      containers:
        - name: nginx-main 
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata:
  name: nginx-np-service 
  labels: 
    app: nginxnp 
spec:
  type: NodePort
  selector:
    app: nginxnp 
  ports:
  - port: 80
    targetPort: 80