apiVersion: apps/v1 
kind: Deployment
metadata:
  name: multi-container-pod-deploy 
  labels:
    app: busybox 
spec:
  replicas: 5
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      name: multi-container-pod 
      labels:
        app: busybox
    spec:
      containers:
      - name: main-writer    #main
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["while true; do echo $(date) Writing data to shared volume >> /shared/log.txt; sleep 5; done"]
        volumeMounts:
        - name: shared-data2
          mountPath: /shared
      - name: helper-reader    #helper/sidecar
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["tail -f /shared/log.txt"]
        volumeMounts:
        - name: shared-data2
          mountPath: /shared  
      volumes:
      - name: shared-data2
        emptyDir: {}