apiVersion: v1 
kind: Pod
metadata:
  name: multi-container-pod 
spec:
  containers:
  - name: main-writer    #main
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["while true; do echo $(date) Writing data to shared volume >> /shared/log.txt; sleep 5; done"]
    volumeMounts:
    - name: shared-data
      mountPath: /shared
  - name: helper-reader    #helper/sidecar
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["tail -f /shared/log.txt"]
    volumeMounts:
    - name: shared-data
      mountPath: /shared  
  volumes:
  - name: shared-data 
    emptyDir: {}